# Generated by Django 6.0.4 on 2026-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
